data::DataLoader
MySQL data.DataLoader.aMySQL
String data.DataLoader.aFilePath
String data.DataLoader.aServer
String data.DataLoader.aPort
String data.DataLoader.aDatabase
String data.DataLoader.aUser
String data.DataLoader.aPassword
data.DataLoader.DataLoader(String pServer, String pPort, String pDatabase, String pUser, String pPassword, String pFilePath)
DataLoader constructeur.
pServer Adresse du serveur pPort Port du serveur pDatabase Nom de la base pUser Login pPassword Mot de passe pFilePath Répertoire où se trouvent les fichiers
void data.DataLoader.mLoadData()
mLoadData méthode de lancement des extractions de données
References mysqldb.MySQL.mClose, mysqldb.MySQL.mConnect, data.DataLoader.mEmptyTables, data.DataLoader.mF1_Circuits, data.DataLoader.mF1_Constructors, data.DataLoader.mF1_Country, data.DataLoader.mF1_LapTimes, data.DataLoader.mF1_Locations, data.DataLoader.mF1_Races, data.DataLoader.mF1_Results, data.DataLoader.mF1_Status, data.DataLoader.mVerify_Status.
Referenced by Main.main.
void data.DataLoader.mVerify_Status()
mVerify_Status méthode de vérification de la table status
References mysqldb.MySQL.mConnection, data.DataLoader.mReadFile.
Referenced by data.DataLoader.mLoadData.
void data.DataLoader.mEmptyTables()
mEmptyTables méthode d'effacement des table en base de données
References mysqldb.MySQL.mConnection.
Referenced by data.DataLoader.mLoadData.
void data.DataLoader.mF1_LapTimes()
mF1_LapTimes méthode d'extraction des données de temps de tours du fichier CSV
References mysqldb.MySQL.mConnection, csv.CSVFile.mCurrentLine, csv.CSVFile.mOpen, csv.CSVFile.mReadLine.
Referenced by data.DataLoader.mLoadData.
void data.DataLoader.mF1_Results()
mF1_Country méthode d'extraction des données de résultats du fichier CSV
References mysqldb.MySQL.mConnection, data.DataLoader.mReadFile.
Referenced by data.DataLoader.mLoadData.
void data.DataLoader.mF1_Constructors()
mF1_Country méthode d'extraction des données d'écuries du fichier CSV
References mysqldb.MySQL.mConnection, data.DataLoader.mReadFile, data.JaroWinkler.similarity.
Referenced by data.DataLoader.mLoadData.
void data.DataLoader.mF1_Country()
mF1_Country méthode d'extraction des données de pays du fichier CSV
References mysqldb.MySQL.mConnection, data.DataLoader.mReadFile, data.JaroWinkler.similarity.
Referenced by data.DataLoader.mLoadData.
void data.DataLoader.mF1_Locations()
mF1_Locations méthode d'extraction des données de villes du fichier CSV
References mysqldb.MySQL.mConnection, data.DataLoader.mReadFile.
Referenced by data.DataLoader.mLoadData.
void data.DataLoader.mF1_Status()
mF1_Status méthode d'extraction des données de status du fichier CSV
References mysqldb.MySQL.mConnection, data.DataLoader.mReadFile.
Referenced by data.DataLoader.mLoadData.
void data.DataLoader.mF1_Circuits()
mF1_Circuits méthode d'extraction des données de circuits du fichier CSV
References mysqldb.MySQL.mConnection, data.DataLoader.mReadFile, data.JaroWinkler.similarity.
Referenced by data.DataLoader.mLoadData.
void data.DataLoader.mF1_Races()
mF1_Races méthode d'extraction des données de courses du fichier CSV
References mysqldb.MySQL.mConnection, data.DataLoader.mReadFile.
Referenced by data.DataLoader.mLoadData.
List<Map<String, String> > data.DataLoader.mReadFile(String pFile)
mReadFile Lit les lignes du fichier CSV donné en paramettres et retourne une liste de champs mappés
pFile Fichier à lire List<Map<String, String>> Liste de champs mappés.
References csv.CSVFile.mReadFile.
Referenced by data.DataLoader.mF1_Circuits, data.DataLoader.mF1_Constructors, data.DataLoader.mF1_Country, data.DataLoader.mF1_Locations, data.DataLoader.mF1_Races, data.DataLoader.mF1_Results, data.DataLoader.mF1_Status, data.DataLoader.mVerify_Status.
void data.DataLoader.mF1_Drivers()
mF1_Drivers méthode d'extraction des données de pilotes du fichier CSV
void data.DataLoader.mShowProgression(int pCounter, int pSize, int pModulo)
mShowProgression méthode outils d'affichage de progression
String data.DataLoader.mPurifyNationalityName(String pNationalityName)
mPurifyNationalityName méthode outils de nétoyage des noms de nationalités du fichier CSV
pNationalityName noms de nationalités à netoyer String noms de nationalités du fichier CSV nétoyé.
String data.DataLoader.mPurifyLocationName(String pLocationName)
mPurifyCircuitsNames méthode outils de nétoyage des noms de circuits du fichier CSV
pCircuitName noms de circuits à netoyer String noms de circuits du fichier CSV nétoyé.
String data.DataLoader.mPurifyCircuitsNames(String pCircuitName)
mPurifyCircuitsNames méthode outils de nétoyage des noms de circuits du fichier CSV
pCircuitName noms de circuits à netoyer String noms de circuits du fichier CSV nétoyé.
String data.DataLoader.mPurifyCountryName(String pCountryName)
mPurifyCountryName méthode outils de nétoyage des noms de pays du fichier CSV
pCountryName noms de pays à netoyer String noms de pays du fichier CSV nétoyé.
String data.DataLoader.mPurifyTime(String pTime)
mPurifyTime méthode outils de nétoyage des heures du fichier CSV
pTime Heure à netoyer String heure du fichier CSV nétoyé.
Double data.DataLoader.mTimeToDouble(String pTime)
mTimeToDouble Convertis une heure du fichier CSV en Double objet
Double heure du fichier CSV convertie en Double.
List<Location> data.DataLoader.mLocations()
mLocations retourne une liste de villes estraits de la bases
List<Location> liste de villes extraits de la base.
List<Country> data.DataLoader.mCountries()
mCountries retourne une liste de pays extraits de la base
List<Country> liste de pays extraits de la base.