data::JaroWinkler
final double data.JaroWinkler.DEFAULT_THRESHOLD
final int data.JaroWinkler.THREE
final double data.JaroWinkler.JW_COEF
double data.JaroWinkler.threshold
Referenced by data.JaroWinkler.getThreshold, data.JaroWinkler.JaroWinkler.
data.JaroWinkler.JaroWinkler()
Instantiate with default threshold (0.7).
References data.JaroWinkler.threshold.
data.JaroWinkler.JaroWinkler(final double threshold)
Instantiate with given threshold to determine when Winkler bonus should be used.
Set threshold to a negative value to get the Jaro distance. threshold
References data.JaroWinkler.threshold.
static double data.JaroWinkler.getThreshold()
Returns the current value of the threshold used for adding the Winkler bonus.
The default value is 0.7. the current value of the threshold
References data.JaroWinkler.threshold.
Referenced by data.JaroWinkler.similarity.
static double data.JaroWinkler.similarity(final String s1, final String s2)
Compute Jaro-Winkler similarity.
s1 The first string to compare. s2 The second string to compare. The Jaro-Winkler similarity in the range [0, 1] NullPointerException if s1 or s2 is null.
References data.JaroWinkler.getThreshold, data.JaroWinkler.matches.
Referenced by data.JaroWinkler.distance, data.DataLoader.mF1_Circuits, data.DataLoader.mF1_Constructors, data.DataLoader.mF1_Country.
static double data.JaroWinkler.distance(final String s1, final String s2)
Return 1 - similarity.
s1 The first string to compare. s2 The second string to compare. 1 - similarity. NullPointerException if s1 or s2 is null.
References data.JaroWinkler.similarity.
static int [] data.JaroWinkler.matches(final String s1, final String s2)
Referenced by data.JaroWinkler.similarity.