.TH "MySQL.MySQL" 3 "Lundi 13 Janvier 2020" "Version 0.57b" "DataLoader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MySQL.MySQL
.SH SYNOPSIS
.br
.PP
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBMySQL\fP (String pServer, String pPort, String pDatabase, String pUser, String pPassword)"
.br
.ti -1c
.RI "void \fBmConnect\fP ()"
.br
.ti -1c
.RI "Connection \fBmConnection\fP ()"
.br
.ti -1c
.RI "void \fBmClose\fP ()"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 7 du fichier MySQL\&.java\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "MySQL\&.MySQL\&.MySQL (String pServer, String pPort, String pDatabase, String pUser, String pPassword)"

.PP
Définition à la ligne 15 du fichier MySQL\&.java\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "void MySQL\&.MySQL\&.mClose ()"

.PP
Définition à la ligne 44 du fichier MySQL\&.java\&.
.SS "void MySQL\&.MySQL\&.mConnect ()"

.PP
Définition à la ligne 22 du fichier MySQL\&.java\&.
.SS "Connection MySQL\&.MySQL\&.mConnection ()"

.PP
Définition à la ligne 37 du fichier MySQL\&.java\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour DataLoader à partir du code source\&.
