mysqldb::MySQL
String mysqldb.MySQL.aURL
String mysqldb.MySQL.aUser
String mysqldb.MySQL.aPassword
Connection mysqldb.MySQL.aConnexion
mysqldb.MySQL.MySQL(String pServer, String pPort, String pDatabase, String pUser, String pPassword)
Instancie une nouvelle connection MySQL en enregistrant les paramêtres de la connection.
pServer Adresse du serveur de base de données pPort Port du serveur de base de données pDatabase Nom de la base de donnée pUser Nom de l'utilisateur à utiliser pour se connecter pPassword Mot de passe de l'utilisateur à utiliser pour se connecter
void mysqldb.MySQL.mConnect()
Se connecte à la base de donnée avec les informations transmisent au constructeur.
References mysqldb.MySQL.mClose.
Referenced by data.DataLoader.mLoadData.
Connection mysqldb.MySQL.mConnection()
mConnection Retourne la connection en cour
Connection Connection actuelle
Referenced by data.DataLoader.mVerify_Status, data.DataLoader.mEmptyTables, data.DataLoader.mF1_LapTimes, data.DataLoader.mF1_Results, data.DataLoader.mF1_Constructors, data.DataLoader.mF1_Country, data.DataLoader.mF1_Locations, data.DataLoader.mF1_Status, data.DataLoader.mF1_Circuits, data.DataLoader.mF1_Races.
void mysqldb.MySQL.mClose()
mClose Ferme la Connection actuelle
Referenced by data.DataLoader.mLoadData, mysqldb.MySQL.mConnect.