csv::CSVFile
CSVReader csv.CSVFile.aCSVReader
int csv.CSVFile.aHeaderLine
int csv.CSVFile.aLineCount
String [] csv.CSVFile.aHeader
String csv.CSVFile.aCSVFilePath
csv.CSVFile.CSVFile(String pCSVFilePath, int pHeaderLine)
CSVFile Constructor.
pCSVFilePath : Path of the csv file to handle pHeaderLine : Number of the header line. < 1 => no header line.
List<Map<String, String> > csv.CSVFile.mReadFile()
mReadFile() Return the list of lines of the CSVFile Mapped with header
A list of lines Mapped with header IOException CsvException
Referenced by data.DataLoader.mReadFile.
void csv.CSVFile.mOpen()
mOpen() Open a file
A list of lines Mapped with header IOException CsvException
Referenced by data.DataLoader.mF1_LapTimes.
Map<String, String> csv.CSVFile.mReadLine()
mReadLine read next line
Map<String, String> if there is a line to read else null IOException CsvException
Referenced by data.DataLoader.mF1_LapTimes.
void csv.CSVFile.mClose()
mClose close any opened file as needed
int csv.CSVFile.mCurrentLine()
mCurrentLine return index of current readed line
index of current readed line
Referenced by data.DataLoader.mF1_LapTimes.
void csv.CSVFile.mShowProgression(int pCounter, int pSize, int pModulo)
mShowProgression Show progression
pCounter Counter current value of monitored value pSize Maximum count of monitored value pModulo Modulo to refresh